app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.

*/

#home


Route::get('/', array('as'=>'home','uses' => 'HomeController@getIndex'));

Route::get('about', array(
    'as' => 'about',
    'uses' => 'HomeController@getAbout'
));

#search
Route::group(array('namespace' => 'Search', 
	'prefix' => 'search'), 
	function()
	{
    	Route::post('/contacts', array(
    		'before' => 'csrf',
    		'as' => 'contacts',
    		'uses' => 'SearchController@contacts'
    		));
	});

Route::resource('search', 'SearchController', ['only' => ['index']]);

#registration
Route::get('register/confirm',array(
    'as' => 'confirm',
    'uses' => 'RegistrationController@confirm'
    ));

Route::get('register/confirmed/{username}/{code}', [
    'as' => 'confirmed', 
    'uses' => 'RegistrationController@confirmed'
]);

Route::get('register', array('as'=>'register', 'uses'=>'RegistrationController@create'));
Route::resource('registration', 'RegistrationController', array('only' => array('create', 'confirm', 'confirmed', 'store')));

#Authentication
Route::get('login', ['as'=> 'login', 'uses' => 'SessionsController@create']);
Route::get('logout', 'SessionsController@destroy');

Route::resource('sessions', 'SessionsController' );

Route::get('password/remind', 'RemindersController@getRemind');
Route::post('password/remind', 'RemindersController@postRemind');
Route::controller('password', 'RemindersController');

Route::get('/profile', ['as' => 'profile', 'uses' => 'ProfilesController@index']);
Route::get('/{profile}', ['as' => 'profile', 'uses' => 'ProfilesController@show']);
Route::resource('profile', 'ProfilesController', ['only' => ['index', 'show', 'edit']]);
Route::resource('users.profiles', 'UserProfileController', ['only' => ['store', 'update']]);
Route::resource('photo', 'PhotoController');


#organisations

//Route::get('/organisation/{id}/users', ['as' => 'members', 'uses' => 'SearchController@show']);

Route::resource('organisation', 'OrganisationsController');
Route::post('/organisation/{organisations}/user/{users}/connect', ['as'=>'organisations.users.connect', 'uses'=>'OrganisationUserController@store']);
Route::resource('organisations.users', 'OrganisationUserController', array('only' => array('update', 'destroy','index')));
Route::resource('organisations.children', 'OrganisationChildController', array('only' => array('update')));



Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function()
{
        Route::group(['before' => 'role:admin'], function()
        {
            
        });
        
        Route::get('login', ['as' => 'admin.login', 'uses' => 'SessionsController@create']);
        Route::resource('sessions', 'SessionsController',  array('only' => array('create', 'store', 'destroy')));
});

app/models/Organisation.php
<?php 
class Organisation extends Node 
{
	protected $table = 'organisations';
    protected $primaryKey = 'id';

    protected $fillable = [
    'name',
    'email',
    'member_type_id',
    'description',
    'announcement', 
    'private_announcement',
    'address',
    'city',
    'zip',
    'country_id', 
    'parent_id', 
    'parent_acceptance'];
    
    protected $guarded = array('id');

    public static function boot()
    {
        parent::boot();

        static::creating(function($model)
        {
            $key = md5('id.'.$model->id);
            Cache::tags('organisations')->flush($key);
        });

        static::saving(function($model)
        {
            $key = md5('id.'.$model->id);
            Cache::tags('organisations')->flush($key);
        });

        static::deleting(function($model)
        {
            $key = md5('id.'.$model->id);
            Cache::tags('organisations')->flush($key);
        });
    }

    public function users()
    {
    	return $this->belongsToMany('User', 'organisation_role_user', 'organisation_id', 'user_id')->withPivot('role_id','accepted');
    }

    public function roles()
    {
        return $this->belongsToMany('Role', 'organisation_role_user', 'organisation_id', 'role_id')->withPivot('user_id','accepted');
    }

    public function photos()
    {
    	return $this->morphMany('Photo', 'imageable');
    }

    public function country()
    {
        return $this->belongsTo('Country');
    }

    public function parent()
    {
        //return $this->hasOne('Category', 'category_id', 'parent_id');

        return $this->belongsTo('Organisation', 'parent_id');
    }

    public function children()
    {
        return $this->hasMany('Organisation','parent_id');
    }

    public function scopeSearch($query, $search)
    {
        return $query->where(function($query) use ($search){
            $query->where('name', 'LIKE', "%$search%")->orWhere('address','LIKE',"%$search%");
        });
    }
}
?>

app/controllers/OrganisationsController.php
<?php  
use Looll\Forms\OrganisationForm;
use Looll\Repo\Organisation\OrganisationInterface;
use Looll\Repo\Country\CountryInterface;

class OrganisationsController extends BaseController
{
	protected $organisation;
	protected $country;
	protected $organisationForm;

	public function __construct(OrganisationForm $organisationForm, OrganisationInterface $organisation, CountryInterface $country)
	{
		$this->organisationForm = $organisationForm;
		$this->organisation = $organisation;
		$this->country = $country;
		
		$this->beforeFilter('csrf', ['only' => ['update','store']]);
		$this->beforeFilter('auth', ['only' => ['update','create','edit','store']]);
		$this->beforeFilter('currentOrganisation', ['only' => ['edit', 'update', 'destroy']]);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$images = array();
		$organisation = array();
		$countries = array();
		$country_id = 265;
		$member_type_id = 3;
		$id = 0;
		$description = "";
		$announcement = "";
		$private_announcement = "";
		$parents = $this->organisation->getParents($id, $member_type_id);	
		$countries = $this->country->getAll();
		
		$contacts = array();	

		$organisation_id = 0;
		$parent_id = 0;

		$url = array('organisation.store');
		$method = 'POST';

		if (count($parents)) 
		{
			$parents['0'] = Lang::get('looll.NoOrganisationSelected');
		}

		return View::make('organisation/create', compact(
			'images', 
			'organisation', 
			'description',
			'private_announcement',
			'announcement',
			'id',
			'organisation_id', 
			'member_type_id', 
			'url', 
			'method', 
			'countries', 
			'country_id', 
			'parent_id', 
			'parents', 
			'contacts'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		(array) $input = (array) Input::all();
		(int) $countryId = (int) $input['country_id'];
		(int) $parentId = (int) $input['parent_id'];
		(string) $username = (string) Auth::user()->username;
		(int) $userId = (int) Auth::id();	
		(bool) $ajax = (bool) Request::ajax();

		$input = Input::only('name','email','member_type_id','description','announcement', 'private_announcement', 'address', 'city', 'zip');
		
		(bool) $validate = (bool) $this->organisationForm->validate($input);
		(string) $redirect = (string) route('profile.edit', $username);

		if ($validate) 
		{
			$organisation = $this->organisation->create($input, $countryId, $parentId, $userId);

			if(!Request::ajax())
			{
				return Redirect::route('profile.edit', $username);
			}
		}

		$messages = array();
		(object) $errors = (object) $this->organisationForm->getValidationErrors();
		(array) $messages = (array) $errors->toArray();

		$messages['validate'] = $validate;
		$messages['redirect'] = $redirect;

		if(Request::ajax())
		{
			return Response::json($messages);
		}

		return Redirect::back()->withInput()->withErrors($errors);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		(array) $associated_organizations = array();
		(array) $images = array();
		(array) $contacts = array();
		(array) $associated_organizations = array();
		(int) $organisation_count = 0;
		(string) $name = "";
		(int) $user_id = 0;

		$organisation = $this->organisation->getById($id);
		if(isset($organisation))
		{
			$contacts = $this->organisation->getUsers($id, 2, 1, 1);
			$members = $this->organisation->getUsers($id, 3, 1, 1);

			$associated_organizations = $this->organisation->getChildren($id, 1);
			$images = $this->organisation->getPhotos($id);

			if (Auth::check()) 
			{
				$user = Auth::user();
				$user_id = Auth::id();

				$organisation_count = $this->organisation->getUsersCount($id, $user_id);
			}

			return View::make('organisation/show', compact(
				'organisation',
				'id',
				'user_id', 
				'name',
				'members', 
				'images', 
				'organisation_count', 
				'contacts', 
				'associated_organizations'
			));


		}

		return Redirect::home();	
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		(array) $contacts = array();
		(array) $members = array();
		(array) $organisation = array();
		(array) $countries = array();
		(int)	$parent_id = 0;
		(string) $description = "";
		(string) $announcement = "";
		(string) $private_announcement = "";

		$organisation = $this->organisation->getById($id);

		if(!isset($organisation))
		{
			return Redirect::route('home');
		}

		$url = array('organisation.update', $id);
		$method = 'PUT';
		
		$parent_id = $organisation->parent_id;
		$countries = $this->country->getAll();

		$country_id = $organisation->country_id;
		$member_type_id = $organisation->member_type_id;
		$parents = $this->organisation->getParents($id);
		
		$accepted = 0;
		$roleId = 2;
		$active = 1;

		$contacts = $this->organisation->getUsers($id, $roleId, $accepted, $active);
		$contacts_counts = count($contacts);
		
		$roleId = 3;
		$users = $this->organisation->getUsers($id, $roleId, $accepted, $active);
		$children = $this->organisation->getChildren($id, 0);

		$description = $organisation->description;
		$private_announcement = $organisation->private_announcement;
		$announcement = $organisation->announcement;
		
		if (count($parents)) 
		{
			$parents['0'] = Lang::get('looll.NoOrganisationSelected');
		}
		
		return View::make('organisation/edit', compact(
			'organisation',
			'announcement',
			'private_announcement',
			'description',
			'parent_id',
			'children', 
			'contacts', 
			'contacts_counts', 
			'users',
			'parents' , 
			'url',
			'method', 
			'id',
			'countries', 
			'country_id', 
			'member_type_id'
		));		
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		(array) $input = array();
		(array) $messages = array();
		(string) $username = (string) "";
		(int) $userId = (int) 0;
		(int) $parentId = (int) 0;
		(int) $countryId = (int) 0;
		(string) $redirect = "";
		(bool) $validate = (bool) false;

		if(!isset($input['parent_id'])) $input['parent_id'] = 0;
		if(!isset($input['country_id'])) $input['country_id'] = 265;

		$parentId = $input['parent_id'];
		$countryId = $input['country_id'];
		$username = Auth::user()->username;
		$userId = Auth::id();

		$input = Input::only(
			'name', 
			'email', 
			'member_type_id', 
			'description', 
			'announcement', 
			'private_announcement', 
			'address', 
			'city', 
			'zip');

		$validate = $this->organisationForm->excludeNameEmailId($id)->validate($input);

		if ($validate) 
		{
			$this->organisation->update($id, $input, $countryId, $parentId);

			if(!Request::ajax())
			{
				return Redirect::route('profile.edit', $username);
			}
		}

		(object) $errors = (object) $this->organisationForm->getValidationErrors();
		$redirect = route('profile.edit', $username);

		$messages = (array) $errors->toArray();
		$messages['validate'] = $validate;
		$messages['redirect'] = $redirect;

		if(Request::ajax())
		{
			return Response::json($messages);
		}
			
		return Redirect::back()->withInput()->withErrors($errors);

	}

	
	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		(object) $photos = $this->organisation->photos($id);

		if(!empty($photos))
		{
			foreach ($photos as $photo) 
			{
				if (File::exists($photo->path)) 
				{
					File::delete($photo->path);
				}
				
				$photo->delete();
			}

		}

		$this->organisation->destroy($id);
	}
}

?>

app/views/organisation/addContact.blade.php
<tr id="deleteContact{{$userId}}">
	<td>{{$user->profile->name}}</td>
	<td><a href="" class="removeContact btn btn-danger" id="removeContact{{$userId}}" data-contacts-count="{{$contacts_count}}" data-organisation-id="{{$organisationId}}" data-user-id="{{$userId}}">@lang('looll.Delete')</a></td>
</tr>

app/views/organisation/create.blade.php
@extends('layouts.master')
@section('content')
		<div class="col-sm-3 search-box">
			<div id="result">
			</div>
		</div>
		{{ Form::open(array('route' => 'organisation.store')) }}
			@include("includes.organisation.form")
			
			<div class="col-sm-4 search-box">
			</div>
		{{ Form::close() }}
@stop

@section('javascript')
	<script type="text/javascript" src="/js/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="/js/jquery-te-1.4.0.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/bootswatch.js"></script>
    <script type="text/javascript" src="/js/organisation.js"></script>
    <script type="text/javascript" src="/js/script.js"></script>
    <script type="text/javascript" src="/js/modernizr.custom.js"></script>
    <script type="text/javascript">
		$('textarea').jqte();
	</script>
@stop

app/views/organisation/edit.blade.php
@extends('layouts.master')
@section('content')
	<div class="row">
		<div class="col-sm-3 box">
				@if(count($organisation))
				
					<div class="panel panel-default organisation-image form-images @if($organisation->photos()->count() == 5) hidden @endif">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a data-toggle="collapse" data-parent="#accordion" href="#organisation-image">@lang('looll.Images')</a>
								</h4>
							</div>
							<div id="organisation-image" class="panel-collapse collapse">
								<div class="panel-body">
									<div class="form-group form-images">
										<div id="droparea" data-organisation-id="{{$id}}" data-profile-id="0">
											<div class="dropareainner">
												<p class="dropfiletext">@lang('looll.DropFilesHere')</p>
												<p>@lang('looll.Or')</p>
												<p>
														<input id="uploadbtn" type="button" class="btn btn-primary" value="@lang('looll.SelectFiles')"/>
												</p>
															<!-- extra feature -->
												<p id="err"><!-- error message --></p>
											</div>
											<input id="upload" type="file" multiple="" />
										</div>
									</div>
								</div>
							</div>
					</div>
				@endif
				<div id="result">
					@if(count($organisation) && $organisation->photos()->count())
						@foreach($organisation->photos()->get() as $photo)
							<div class="imageholder" id="imageholder{{{$photo->id}}}">
								<figure>
										{{ HTML::image($photo->src, $alt=$photo->name, $attributes = array("class"=>"image", "data-image-id" => $photo->id)) }}
										<span class="fa fa-times-circle remove-images" data-organisation-id="{{$id}}" data-profile-id="0" data-image-id="{{{$photo->id}}}"></span>
								
										<span class="fa @if($photo->image_primary) fa-star @else fa-star-o @endif primary-image" data-organisation-id="{{$id}}" data-profile-id="0" data-image-id="{{{$photo->id}}}" data-primary="{{$photo->image_primary}}"></span>
								</figure>
							</div>
						@endforeach
					@endif
				</div>
		</div>
		{{ Form::model($organisation, array('route' => $url, 'data-remote', 'novalidate', 'method' => 'PUT')) }}
			@include("includes.organisation.form")
			<div class="col-sm-4 box">
				<div class="panel-group" id="accordion">
						@if($member_type_id == 3 && count($children) > 0)
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordion" href="#organisationsMembers">
											@lang('looll.AssocitedMembers')
										</a>
									</h4>
								</div>
								<div id="organisationsMembers" class="panel-collapse collapse">
									<div class="panel-body">
										<table class="table">
											<thead>
												<tr>
														<th>@lang('looll.Organisation')</th>
														<th>@lang('looll.Action')</th>
												</tr>
											</thead>
											<tbody>
													@if(count($children))
														@foreach($children as $child)
															<tr>
																<td>{{link_to_route('organisation.show', $title = $child->name, $parameters = array('id'=>$child->id), $attributes = array()) }}</td>
																<td>
																		<button data-url="{{ route('organisations.children.update', array('id' => $id, 'organisation_id'=>$child->id)) }}" id="accept{{$child->id}}" class="acceptGroup btn @if($child->parent_acceptance == 1) hidden @endif btn-primary">@lang('looll.Accept')</button>
																		<button data-url="{{ route('organisations.children.update', array('id' => $id, 'children'=>$child->id)) }}" id="decline{{$child->id}}" class="declineGroup btn @if($child->parent_acceptance == 0) hidden @endif btn-warning">@lang('looll.Decline')</button>
																</td>
															</tr>
														@endforeach
													@endif
											</tbody>
										</table>
									</div>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
										<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordion" href="#usersMembers">
											@lang('looll.UserMembers')
										</a>
										</h4>
								</div>
								<div id="usersMembers" class="panel-collapse collapse">
										<div class="panel-body">
											<table class="table">
												<thead>
													<tr>
														<th>@lang('looll.Name')</th>
													</tr>
												</thead>
												<tbody>
													@foreach($children as $child)
														@if($child->member_type_id == 2)
															@foreach($child->users()->get() as $user)
																<tr>
																	<td>{{ $user->username }}</td>
																</tr>
																@if(isset($user->profile->name))
																	<tr>
																		<td>{{ $user->profile->name }}</td>
																	</tr>
																@endif
															@endforeach
														@endif
													@endforeach
												</tbody>
											</table>
										</div>	
								</div>
							</div>
						@elseif($member_type_id == 2 && count($users) > 0)
								<div class="panel panel-default">
										<div class="panel-heading">
												<h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#usersMembers">@lang('looll.UserMembers')</a></h4>
										</div>
										<div id="usersMembers" class="panel-collapse collapse">
												<div class="panel-body">
														<table class="table">
																<thead>
																		<tr>
																				<th>@lang('looll.Name')</th>
																				<th>@lang('looll.Action')</th>
																		</tr>	
																</thead>
																<tbody>
																		<tr>
																				@foreach($users as $user)
																						@if(isset($user->profile))
																								<tr id="deleteUser{{$user->id}}">
																										<td>
																											{{
																													link_to_route('profile', $user->profile->name, array('username' => $user->username), array("target" => "_blank"));
																											}}
																										</td>
																										<td>
																												<button data-user-id="{{$user->id}}" data-organisation-id="{{$id}}" id="acceptUser{{$user->id}}" class="acceptUser btn @if($user->pivot->accepted == 1 ) hidden @endif btn-primary btn-sm">@lang('looll.Accept')</button>
																												<button data-user-id="{{$user->id}}" data-organisation-id="{{$id}}" id="declineUser{{$user->id}}" class="declineUser btn @if($user->pivot->accepted == 0) hidden @endif btn-warning btn-sm">@lang('looll.Decline')</button>
																												<button class="removeUser btn btn-warning btn-sm" data-user-id="{{$user->id}}" data-organisation-id="{{$id}}">@lang('looll.Remove')</button></td>
																								</tr>
																						@endif
																				@endforeach
																		</tr>
																</tbody>
														</table>
												</div>
										</div>
								</div>
						@endif
				</div>
			</div>
		{{ Form::close() }}
	</div>
@stop
@section('javascript')
		<script src="/js/organisations/dist/main.bundle.min.js?v=1.4"></script>
		<script type="text/javascript">
				$('textarea').jqte();
		</script>
    <script type="text/javascript" src="/js/modernizr.custom.js"></script>
@stop

app/views/organisation/show.blade.php
@extends('layouts.master')
@section('content')
	<div class="row">
		<div class="col-lg-12">
          <div class="page-header">
            <h1>{{{$organisation->name}}}</h1> 
          </div>
        </div>
	</div>
	<div class="row">
		<div class="col-sm-3">
			@if(!empty($images))
				<div class="row">
					<div class="col-sm-12">
						@foreach($images as $image)
			                @if($image->image_primary == 1)
			                	<img src="{{{$image->src}}}" alt="{{{$image->name}}}" class="img-thumbnail" />
			                @endif
			            @endforeach
					</div>
				</div>
				<div class="row">
					<div class="col-sm-12">
						<div class="crop">
			                @foreach($images as $image)
			                  @if($image->image_primary == 0)
			                      <img src="{{{$image->src}}}" alt="{{{$image->name}}}" class="img-thumbnail" />
			                  @endif
			                @endforeach  
			            </div>
					</div>
				</div>
			@endif
		</div>
		<div class="col-sm-6">
			<div class="row">
				<div class="col-sm-6">
					<div class="panel panel-default">
						<div class="panel-heading">
							<h4 class="panel-title">@lang('looll.Information')</h4>
						</div>
						<div class="panel-body">
							<address>
				                {{{$organisation->address}}}<br>
				                {{{$organisation->zip}}} {{{$organisation->city}}}<br>
				                @if($organisation->country()->count() > 0)
				                	{{{$organisation->country()->first()->name}}}<br />
				                @endif
				                {{{$organisation->email}}}
				            </address>
				              <h5>@lang('looll.Contacts')</h5>
				            <address>
				                @foreach($contacts as $contact)
				                  <a href="/{{$contact->username}}">{{$contact->profile->name}}</a><br />           
				                @endforeach
				            </address>
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="panel panel-default">
						<div class="panel-heading">
							<h4 class="panel-title">@lang('looll.About', array('name'=>$organisation->name))</h4>
						</div>
						<div class="panel-body">
							{{$organisation->description}}
						</div>
					</div>
					
				</div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<div class="panel panel-default">
						<div class="panel-heading">
							<h4 class="panel-title">@lang('looll.Announcement')</h4>
						</div>
						<div class="panel-body">
							{{$organisation->announcement}}	
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					@if(Auth::check() && $organisation->member_type_id == 2 && $organisation_count == 0)
	                  		<a href="/" class="btn btn-primary pull-right" id="connect" data-user-id="{{$user_id}}" data-organisation-id="{{$id}}" data-token="{{ Form::token() }}">@lang('looll.Connect')</a>              

	              	@endif
				</div>	
			</div>
		</div>
		<div class="col-sm-3">
			<div class="panel-group" id="accordion">
				@if($organisation->member_type_id == 2 && count($members) > 0)
					<div class="panel panel-default">
                        <div class="panel-heading">
                          <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                              @lang('looll.Members')
                            </a>
                          </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse in">
                           <div class="panel-body">
                              <ul class="media-list">
                                @if(count($members))
                                @foreach($members as $member)
                                  @if(isset($member->profile))
                                  	<li><a href="/{{$member->username}}">{{$member->profile->name}}</a></li>
                                  @endif
                                @endforeach
                                @endif
                              </ul>
                           </div>
                        </div>
                      </div>
				@endif
				@if($organisation->member_type_id == 3 && count($associated_organizations) > 0) 
					<div class="panel panel-default">
                        <div class="panel-heading">
                          <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                             @lang('looll.AssociatedOrganizations')
                            </a>
                          </h4>
                        </div>
                        <div id="collapseTwo" class="panel-collapse collapse in">
                         <div class="panel-body">
                              <ul class="media-list">
                              	@if(count($associated_organizations))
                                @foreach($associated_organizations as $associated_organisation)
                                  <li><a href="/organisation/{{$associated_organisation->id}}">{{$associated_organisation->name}}</a></li>
                                @endforeach
                                @endif
                              </ul>
                           </div>
                        </div>
                    </div>
				@endif
			</div>
		</div>
	</div>
@stop
@section('javascript')
	<script type="text/javascript" src="/js/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="/js/jquery-te-1.4.0.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/bootswatch.js"></script>
    <script type="text/javascript" src="/js/organisation.js"></script>
    <script type="text/javascript" src="/js/script.js"></script>
    <script type="text/javascript" src="/js/modernizr.custom.js"></script>
	
@stop